### ISSUE TITLE
Add support for HTTPS links

### ISSUE THREAD

**Issue by pureooze** [ForeEyes/PodcastFeed#10]
The program should be able to download podcasts/RSS from HTTPS links. This does not work at the moment and results in an error (see below).

**Link submission:**
![image](https://cloud.githubusercontent.com/assets/2337524/24119931/421b28dc-0d89-11e7-93e0-e259b5123066.png)

**Error message:**
![image](https://cloud.githubusercontent.com/assets/2337524/24119974/627aafc6-0d89-11e7-9a1c-ade682a649f3.png)

**Debug output:**
![image](https://cloud.githubusercontent.com/assets/2337524/24119950/4d9d163e-0d89-11e7-8018-a9d44e60f703.png)

**Comment by pureooze** [comment]
I'm using the same project file as the one that is on the repo and it has that line in it.

![image](https://cloud.githubusercontent.com/assets/2337524/24121412/91773538-0d8e-11e7-9151-f11a03cc87d3.png)

**Comment by pureooze** [comment]
This still occurs when compiling using MSVC 2015 (64 bit):
![image](https://cloud.githubusercontent.com/assets/2337524/24128567/153ca992-0db3-11e7-812c-948fc7aea216.png)

![image](https://cloud.githubusercontent.com/assets/2337524/24128576/25fdd6d4-0db3-11e7-8b24-6550b31cc5fa.png)

**Comment by pureooze** [comment]
This may be related. Can you check to see if you have these libraries somewhere in PATH? 
https://stackoverflow.com/questions/18894056/error-creating-ssl-context-qt

**Comment by ForeEyes** [comment]
It might be the microsoft visual C++ 2008 redistributable, because i have that, or a later version of that(i have the 2015 version that got installed with visual studio 2015 community edition).
As for the system32 files, i do not have those.
This should not be a problem when the application is packaged, as qt will include those...

**Comment by pureooze** [comment]
Yeah I have it installed too, not sure what is causing this as I have Visual Studio 2015 Enterprise installed with the C++ stuff that comes with it.

**Comment by pureooze** [comment]
I asked a friend to try compiling and running this, and he has the same error. Seems like some missing libs...

**Comment by ForeEyes** [comment]
Check this response on stackoverflow : "We determined it was because, although we weren't using SSL either, the program found a copy of OpenSSL on the customer's computer and tried interfacing with it. The version it found was too old though (from Qt 5.2 onwards v1.0.0 or later is required).

Our solution was to distribute the OpenSSL DLLs along with our application (~1.65 MB). The alternative is to compile Qt from scratch without OpenSSL support."

**Comment by ForeEyes** [comment]
ok, so i manually tried the html page, and it also works. So go to the get rssurl function and change https to http in the url variable.

**Comment by ForeEyes** [comment]
**Try this release, go into the release folder and run the .exe** 
[build-PodcastFeed-Desktop_Qt_5_8_0_MSVC2015_64bit-Release.zip](https://github.com/ForeEyes/PodcastFeed/files/859027/build-PodcastFeed-Desktop_Qt_5_8_0_MSVC2015_64bit-Release.zip)

file in the folder.

**Comment by ForeEyes** [comment]
If you still get the error, get the opensll dll from this link:http://slproweb.com/products/Win32OpenSSL.html****
either install the opensll or include the dll's in the release folder...

**Comment by ForeEyes** [comment]
never mind, just tested it, does not work....
I will try to create another build with the openssl dll's...

**Comment by ForeEyes** [comment]
Alright, figured it out... you need libeay32.dll and ssleay32.dll. These files are in the qt creator bin folder (after i did a clean install 😑 ). I moved them to the folder with the executable and it works....

Here is the new release build:
[build-PodcastFeed-Desktop_Qt_5_8_0_MSVC2015_32bit-Release.zip](https://github.com/ForeEyes/PodcastFeed/files/859410/build-PodcastFeed-Desktop_Qt_5_8_0_MSVC2015_32bit-Release.zip)

**Comment by ForeEyes** [comment]
Here are the files, incase you need them...
[openssl_DLL.zip](https://github.com/ForeEyes/PodcastFeed/files/859440/openssl_DLL.zip)

**Comment by pureooze** [comment]
Issue seems to be solved now by using those dll files. I'm not sure if we can consider this a perfect solution but I guess its good enough to close the issue.
