### ISSUE TITLE
Encapsulating podcast information using a Class

### ISSUE THREAD

**Issue by pureooze** [ForeEyes/PodcastFeed#13]
We may want to think about using a Podcast class to encapsulate all the information pertaining to an individual podcast. It seems many of the properties like filepaths, names and episode lists could be encapsulated to make it a bit easier and cleaner to write the code. Thoughts?

**Comment by ForeEyes** [comment]
dude, its like 2 am go watch a movie or something....
Ya after i finish with the description, i will work on creating a podcast class...

**Comment by pureooze** [comment]
I had just finished with my part for the playback and it came to my mind so I didnt want to forget it lol.

**Comment by pureooze** [comment]
This is resolved now with the podcastManager class now right?

**Comment by ForeEyes** [comment]
Yep
