### ISSUE TITLE
Add media playback for podcast audio files

### ISSUE THREAD

**Issue by pureooze** [ForeEyes/PodcastFeed#2]
We should add audio playback functionality for the podcasts. The playback should start when a user clicks the play button, and pause/stop when  a user clicks the respective button. The correct file to play should be determined based on the users CURRENT selection in the episodeList.

**Comment by pureooze** [comment]
I have made some progress on this, check out the following commit in my media-playback branch:
https://github.com/pureooze/PodcastFeed/commit/0d284ab20dd0b4fc5c9549b53f00275b39b1d86d

It can play, pause and seek forward/backwards as needed now. The seek calculation is made using a percentage of the total duration of the audio file. So if for example you seek to the half way point on the seek bar, the calculation would be:
`int time = player->duration() * 0.5`

This value is then used to set the position for the QtMediaPlayer object to reflect that time.

**Comment by ForeEyes** [comment]
`QUrl MainWindow::episodeFile(){
    QString podcastName = ui->PodcastList->currentItem()->text();
    QString episodeName = ui->EpisodeList->currentItem()->text();
    QUrl audioFile;

    QString podcastFilePath = xmlFolder + "/" + podcastName + ".xml";

    QFile xmlFile(podcastFilePath);
    if (!xmlFile.open(QFile::ReadOnly | QFile::Text)) {
        ui->statusBar->showMessage("Cannot load xml file...", 3000);
    }

    QXmlStreamReader xml(&xmlFile);

    bool episodeReached = false;

    while(!xml.atEnd() && !xml.hasError()) {
        // Read next element
        QXmlStreamReader::TokenType token = xml.readNext();
        //If token is just StartDocument - go to next
        if(token == QXmlStreamReader::StartDocument) {
                continue;
        }
        //If token is StartElement - read it
        if(token == QXmlStreamReader::StartElement) {

            if(xml.name() == "title" && xml.prefix().isEmpty() && xml.readElementText() == episodeName){
                episodeReached = true;
            }

            if(xml.name() == "enclosure" && episodeReached) {
                audioFile = xml.attributes().value("url").toString();
                break;
            }
        }
    }
    xmlFile.close();

    return audioFile;
}
`

**Comment by ForeEyes** [comment]
void MainWindow::on_PodcastList_clicked(const QModelIndex &index)
{
    QString podcastName = ui->PodcastList->item(index.row())->text();
    QStringList Episodes;

    QString podcastFilePath = xmlFolder + "/" + podcastName + ".xml";

    QFile xmlFile(podcastFilePath);
    if (!xmlFile.open(QFile::ReadOnly | QFile::Text)) {
        ui->statusBar->showMessage("Cannot load xml file...", 3000);
    }

    QXmlStreamReader xml(&xmlFile);

    bool firstSkipped = false;

    while(!xml.atEnd() && !xml.hasError()) {
        // Read next element
        QXmlStreamReader::TokenType token = xml.readNext();
        //If token is just StartDocument - go to next
        if(token == QXmlStreamReader::StartDocument) {
                continue;
        }
        //If token is StartElement - read it
        if(token == QXmlStreamReader::StartElement) {

            if(xml.name() == "title" && xml.prefix().isEmpty() && firstSkipped) {
                Episodes << xml.readElementText();
            }

            if(xml.name() == "title" && !firstSkipped){
                firstSkipped = true;
            }
        }
    }
    xmlFile.close();

    ui->EpisodeList->clear();
    std::reverse(Episodes.begin(), Episodes.end());
    ui->EpisodeList->addItems(Episodes);
}

void MainWindow::on_EpisodeList_clicked(const QModelIndex &index)
{
    QString podcastName = ui->PodcastList->currentItem()->text();
    QString episodeName = ui->EpisodeList->item(index.row())->text();
    QString episodeDescription;

    QString podcastFilePath = xmlFolder + "/" + podcastName + ".xml";

    QFile xmlFile(podcastFilePath);
    if (!xmlFile.open(QFile::ReadOnly | QFile::Text)) {
        ui->statusBar->showMessage("Cannot load xml file...", 3000);
    }

    QXmlStreamReader xml(&xmlFile);

    bool descriptionReached = false;

    while(!xml.atEnd() && !xml.hasError()) {
        // Read next element
        QXmlStreamReader::TokenType token = xml.readNext();
        //If token is just StartDocument - go to next
        if(token == QXmlStreamReader::StartDocument) {
                continue;
        }
        //If token is StartElement - read it
        if(token == QXmlStreamReader::StartElement) {

            if(xml.name() == "title" && xml.prefix().isEmpty() && xml.readElementText() == episodeName){
                descriptionReached = true;
            }

            if(xml.name() == "description" && descriptionReached) {
                episodeDescription = xml.readElementText();
                break;
            }
        }
    }
    xmlFile.close();

    episodeDescription.insert(0, "<b>Description:</b>");

    ui->Description->clear();
    ui->Description->setHtml(episodeDescription);
}
