### ISSUE TITLE
Dealing with episode URLs that have been relocated

### ISSUE THREAD

**Issue by pureooze** [ForeEyes/PodcastFeed#29]
In some cases it is possible that the URL to a podcast may be retired and relocated somewhere else. In these cases the webserver should send a HTTP 301 code to redirect to the correct URL.

At the time being it seems that this isnt done when using `qDebug() << ((QString)reply->readAll()).toUtf8();`
![image](https://cloud.githubusercontent.com/assets/2337524/24342178/21e7a91a-128d-11e7-8c93-9a72a2edbc96.png)

Will have to look into this to make sure redirection works fine when downloading files. It seems this is not an issue for QMediaPlayer as it follows the redirection without issues. Here is the code I am using:

```C++
// slot to download podcasts
void MainWindow::downloadPodcast()
{
    qDebug() << episodeFile();
    //When the http request is finished, call the storePodcast function
    QObject::connect(manager, SIGNAL(finished(QNetworkReply*)), this, SLOT(storePodcast(QNetworkReply*)));
    //http request
    manager->get(QNetworkRequest(episodeFile()));
}

void MainWindow::storePodcast(QNetworkReply *reply){
    //If there is a reply error then display message
    if (reply->error() == QNetworkReply::NoError) {

        //parse the json reply and get the rss link string
        qDebug() << ((QString)reply->readAll()).toUtf8();

        reply->deleteLater();
    }
    else {
        //reply error, display message
        ui->statusBar->showMessage("Network Request Failed..." + reply->errorString(), 3000);
        reply->deleteLater();
    }
}
```

**Comment by ForeEyes** [comment]
I have already got code to download the files, as i was working on faster buffering and so i have already dealt with and fixed the redirection issue!

**Comment by pureooze** [comment]
Could you share the solution for that? I need to use it for the download podcast functionality.

Thanks

**Comment by ForeEyes** [comment]
```
    QNetworkRequest request;
    request.setUrl(episodeFile());
    **request.setAttribute(QNetworkRequest::FollowRedirectsAttribute, true);**
    reply = manager->get(request);
```
