### ISSUE TITLE
Populate the descriptionPane based on context

### ISSUE THREAD

**Issue by pureooze** [ForeEyes/PodcastFeed#3]
The descriptionPane should be filled with content based on the selection the user makes.

- If the selection is made in the podcastList widget, the descriptionPane should show details about the podcast

- If the selection is made in the episodeList widget, the descriptionPane should show details about the episode

**Comment by holmejmcm** [comment]
Hi Everyone,

I'll do this part.

**Comment by pureooze** [comment]
Resolved by https://github.com/ForeEyes/PodcastFeed/pull/19
